### PR TITLE
version 3.14.0.0 & python3.7

### PR DESCRIPTION
**Pull request by quentin-ol**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Upgrades the recipe to version 3.14.0.0 and python 3.7. and rebuilds the python API for Windows OS.

### CODE REVIEW

**Comment by quentin-ol** [comment]
@conda-forge-admin, please rerender

**Comment by ryanvolz** [comment]
Thanks for the pull request! I haven't had much time to update this lately, but I'll try to take a look soon. It's looking like this most needs a re-render in order to incorporate conda-forge changes.

**Comment by ryanvolz** [comment]
I have the 3.14.0.0 build working now for everything except for Windows with the Python API. Thanks for the push!

**Comment by quentin-ol** [comment]
Hey Ryan, thanks so much for this. The python API for Windows is the part I was looking for. Any pointers on how to start working on it ?

**Pull request closed without merging**
